### ISSUE TITLE
请问下opengpt-serve.toml 这个文件是什么呢,其中需要有什么内容呢

### ISSUE THREAD

**Issue by shininome** [gngpp/opengpt#107]
感谢你的帮助

**Comment by gngpp** [comment]
这个是把命令行配置写在文件，这样就不必要opengpt serve run --xxx xxx --xxx1 xxx1，一大堆了，直接`opengpt serve run -C opengpt-serve.toml`

**Comment by gngpp** [comment]
模版生成命令`opengpt serve gt`

**Comment by shininome** [comment]
> 模版生成命令`opengpt serve gt`
你好,我是使用docker安装,如何使用这条命令呢

**Comment by shininome** [comment]
> 模版生成命令`opengpt serve gt`
```
    volumes:
      # - ${PWD}/ssl:/etc
      - ${PWD}/opengpt-serve.toml:/opengpt-serve.toml
  ```
docker compose 这条要求文件先存在来着

**Comment by gngpp** [comment]
> > 模版生成命令`opengpt serve gt`
> 
> ```
>     volumes:
>       # - ${PWD}/ssl:/etc
>       - ${PWD}/opengpt-serve.toml:/opengpt-serve.toml
> ```
> 
> docker compose 这条要求文件先存在来着

如果没有，不用的可以直接删掉的，不配置证书默认配置就行了

**Comment by shininome** [comment]
> > > 模版生成命令`opengpt serve gt`
> > 
> > 
> > ```
> >     volumes:
> >       # - ${PWD}/ssl:/etc
> >       - ${PWD}/opengpt-serve.toml:/opengpt-serve.toml
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > docker compose 这条要求文件先存在来着
> 
> 如果没有，不用的可以直接删掉的，不配置证书默认配置就行了

感谢,目前遇到的问题主要是无法显示历史记录,无法正常使用,返回的是 500 Internal Server Error

warp报错为
` 2023/08/15 11:30:21 socat[68] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused `

` Error: "Unable to connect to CloudflareWARP daemon. Maybe the daemon is not running?" `

我的docker-compose 如下
```
version: '3'

services:
  opengpt:
    image: ghcr.io/gngpp/opengpt:latest
    container_name: opengpt
    # restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - OPENGPT_PROXY=socks5://cloudflare-warp:40000

    command: serve run
    ports:
      - "8880:7999"
    depends_on:
      - cloudflare-warp

  cloudflare-warp:
    container_name: cloudflare-warp
    image: ghcr.io/gngpp/cloudflare-warp:latest

    # restart: unless-stopped
```
